import os
import json


BASE_DIR = os.path.abspath("../generated_projects")


def create_project_structure(project_name):
    project_path = os.path.join(BASE_DIR, project_name)
    templates_path = os.path.join(project_path, "templates")
    routes_path = os.path.join(project_path, "routes")
    static_path = os.path.join(project_path, "static")
    services_path = os.path.join(project_path, "services")
    tests_path = os.path.join(project_path, "tests")
    data_path = os.path.join(project_path, "data")

    os.makedirs(project_path, exist_ok=True)
    os.makedirs(templates_path, exist_ok=True)
    os.makedirs(routes_path, exist_ok=True)
    os.makedirs(static_path, exist_ok=True)
    os.makedirs(services_path, exist_ok=True)
    os.makedirs(tests_path, exist_ok=True)
    os.makedirs(data_path, exist_ok=True)

    for package_path in (routes_path, services_path):
        init_path = os.path.join(package_path, "__init__.py")
        with open(init_path, "w") as f:
            f.write("")

    return project_path


def render_base_template(project_title):
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{{{ page_title or "{project_title}" }}}}</title>
    <link rel="stylesheet" href="{{{{ url_for('static', filename='style.css') }}}}">
</head>
<body>
    <header class="app-header">
        <div>
            <p class="eyebrow">{project_title}</p>
            <h1>{{{{ page_title or "{project_title}" }}}}</h1>
            <p class="subtitle">{{{{ description or "Generated by the AI Code Generator." }}}}</p>
        </div>
        <nav class="top-nav">
            <a href="{{{{ url_for('home') }}}}">Home</a>
        </nav>
    </header>
    <main class="page-shell">
        {{% with messages = get_flashed_messages(with_categories=true) %}}
            {{% if messages %}}
                <section class="flash-stack">
                {{% for category, message in messages %}}
                    <div class="flash {{'flash-success' if category == 'success' else 'flash-error'}}">{{{{ message }}}}</div>
                {{% endfor %}}
                </section>
            {{% endif %}}
        {{% endwith %}}
        {{% block content %}}{{% endblock %}}
    </main>
</body>
</html>
"""


def render_home_template(module, project_title):
    if module == "crud":
        return """{% extends "base.html" %}
{% block content %}
<section class="hero-card">
    <div>
        <p class="eyebrow">Generated CRUD workspace</p>
        <h2>Role-based resource management starter</h2>
        <p>This starter includes sign-in, dashboard metrics, resource list/search, create/edit pages, detail views, and protected destructive actions.</p>
        <div class="button-row">
            <a class="button primary" href="/login">Open login</a>
            <a class="button secondary" href="/dashboard">Open dashboard</a>
        </div>
    </div>
    <div class="info-panel">
        <h3>Default roles</h3>
        <ul>
            <li>Admin: full create, edit, delete access</li>
            <li>Member: read-only access to list and detail pages</li>
            <li>Seeded demo data appears automatically on first run</li>
        </ul>
    </div>
</section>
{% endblock %}
"""
    module_title = module.replace("_", " ").title()
    return f"""{{% extends "base.html" %}}
{{% block content %}}
<section class="hero-card">
    <div>
        <p class="eyebrow">Generated project</p>
        <h2>{module_title} module ready</h2>
        <p>This starter includes routes, persistence helpers, a success path, a dashboard summary, tests, and a README.</p>
        <div class="button-row">
            <a class="button primary" href="/{module}">Open module</a>
            <a class="button secondary" href="/dashboard">View dashboard</a>
        </div>
    </div>
    <div class="info-panel">
        <h3>What is included</h3>
        <ul>
            <li>Server-side validation</li>
            <li>JSON-backed sample storage</li>
            <li>Companion templates and styling</li>
            <li>Smoke tests and setup instructions</li>
        </ul>
    </div>
</section>
{{% endblock %}}
"""


def render_success_template():
    return """{% extends "base.html" %}
{% block content %}
<section class="hero-card">
    <div>
        <p class="eyebrow">Submission captured</p>
        <h2>{{ module_name }} completed successfully</h2>
        <p>The generated flow stored the submitted payload in the local JSON data store.</p>
        <div class="button-row">
            <a class="button primary" href="{{ url_for('home') }}">Back home</a>
            <a class="button secondary" href="/dashboard">Open dashboard</a>
        </div>
    </div>
    <div class="info-panel">
        <h3>Quick stats</h3>
        <ul>
            <li>Total submissions: {{ stats.total_submissions }}</li>
            <li>Active modules: {{ stats.module_count }}</li>
            <li>Stored categories: {{ stats.categories|join(', ') if stats.categories else 'None yet' }}</li>
        </ul>
    </div>
</section>
{% endblock %}
"""


def render_dashboard_template():
    return """{% extends "base.html" %}
{% block content %}
<section class="metric-grid">
    <article class="metric-card">
        <p>Total submissions</p>
        <h2>{{ stats.total_submissions }}</h2>
    </article>
    <article class="metric-card">
        <p>Active modules</p>
        <h2>{{ stats.module_count }}</h2>
    </article>
    <article class="metric-card">
        <p>Last updated</p>
        <h2>{{ stats.last_updated }}</h2>
    </article>
</section>
<section class="hero-card">
    <div>
        <h3>Recent categories</h3>
        <ul>
            {% for category in stats.categories %}
            <li>{{ category }}</li>
            {% else %}
            <li>No submissions stored yet.</li>
            {% endfor %}
        </ul>
    </div>
    <div class="info-panel">
        <h3>Storage</h3>
        <p>Data is stored locally in <code>data/app_data.json</code> for easy inspection during development.</p>
    </div>
</section>
{% endblock %}
"""


def render_crud_dashboard_template(resource_label):
    return f"""{{% extends "base.html" %}}
{{% block content %}}
<section class="metric-grid">
    <article class="metric-card">
        <p>Total {resource_label.lower()}s</p>
        <h2>{{{{ stats.total_items }}}}</h2>
    </article>
    <article class="metric-card">
        <p>Active items</p>
        <h2>{{{{ stats.active_items }}}}</h2>
    </article>
    <article class="metric-card">
        <p>Draft items</p>
        <h2>{{{{ stats.draft_items }}}}</h2>
    </article>
</section>
<section class="hero-card">
    <div>
        <h3>Management actions</h3>
        <ul>
            <li><a href="/{{{{ resource_plural }}}}">Open table view</a></li>
            <li><a href="/{{{{ resource_plural }}}}/new">Create a new {resource_label.lower()}</a></li>
            <li>Use search and status filters from the list screen</li>
        </ul>
    </div>
    <div class="info-panel">
        <h3>Access summary</h3>
        <p>Signed in as <strong>{{{{ current_role }}}}</strong>. Admin users can create, edit, and delete records.</p>
    </div>
</section>
{{% endblock %}}
"""


def render_crud_login_template():
    return """{% extends "base.html" %}
{% block content %}
<section class="hero-card">
    <div>
        <p class="eyebrow">Role-based auth</p>
        <h2>Sign in to the generated workspace</h2>
        <p>Use one of the seeded demo accounts to explore the CRUD workflow.</p>
        <ul>
            <li>Admin: <code>admin / admin123</code></li>
            <li>Member: <code>member / member123</code></li>
        </ul>
    </div>
    <form method="POST">
        <div class="field">
            <label for="username">Username</label>
            <input id="username" name="username" type="text" required>
        </div>
        <div class="field">
            <label for="password">Password</label>
            <input id="password" name="password" type="password" required>
        </div>
        <button class="button primary" type="submit">Sign in</button>
    </form>
</section>
{% endblock %}
"""


def render_crud_list_template(fields, resource_label, resource_plural):
    searchable_columns = "".join([f"<th>{field['label']}</th>" for field in fields[:4]])
    row_values = "".join([f"<td>{{{{ item.get('{field['name']}', '') }}}}</td>" for field in fields[:4]])
    return f"""{{% extends "base.html" %}}
{{% block content %}}
<section class="hero-card">
    <div>
        <p class="eyebrow">{resource_label} management</p>
        <h2>{{{{ resource_label }}}} table</h2>
        <p>Search, filter, inspect, and manage records from one place.</p>
    </div>
    <form method="GET" action="/{resource_plural}">
        <div class="form-grid">
            <div class="field">
                <label for="q">Search</label>
                <input id="q" name="q" type="text" value="{{{{ query }}}}" placeholder="Search records">
            </div>
            <div class="field">
                <label for="status">Status</label>
                <input id="status" name="status" type="text" value="{{{{ status }}}}" placeholder="active or draft">
            </div>
        </div>
        <div class="button-row">
            <button class="button primary" type="submit">Apply filters</button>
            {{% if role == "admin" %}}<a class="button secondary" href="/{resource_plural}/new">Create {resource_label}</a>{{% endif %}}
        </div>
    </form>
</section>
<section class="hero-card">
    <div style="grid-column: 1 / -1;">
        <table class="table">
            <thead>
                <tr>
                    {searchable_columns}
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {{% for item in items %}}
                <tr>
                    {row_values}
                    <td>
                        <a href="/{resource_plural}/{{{{ item.id }}}}">View</a>
                        {{% if role == "admin" %}}
                        <a href="/{resource_plural}/{{{{ item.id }}}}/edit">Edit</a>
                        <form method="POST" action="/{resource_plural}/{{{{ item.id }}}}/delete" style="display:inline;">
                            <button type="submit" class="link-button">Delete</button>
                        </form>
                        {{% endif %}}
                    </td>
                </tr>
                {{% else %}}
                <tr>
                    <td colspan="{len(fields[:4]) + 1}">No records matched the current filters.</td>
                </tr>
                {{% endfor %}}
            </tbody>
        </table>
    </div>
</section>
{{% endblock %}}
"""


def render_crud_form_template(resource_label, resource_plural):
    return f"""{{% extends "base.html" %}}
{{% block content %}}
<section class="hero-card">
    <div>
        <p class="eyebrow">{resource_label} workflow</p>
        <h2>{{{{ page_title }}}}</h2>
        <p>Capture and validate core record details for this generated CRUD module.</p>
    </div>
    <form method="POST" action="{{{{ action_url }}}}">
        <div class="form-grid">
            {{% for field in fields %}}
            <div class="field {{% if field.type == 'textarea' %}}full{{% endif %}}">
                <label for="{{{{ field.name }}}}">{{{{ field.label }}}}</label>
                {{% if field.type == "textarea" %}}
                <textarea id="{{{{ field.name }}}}" name="{{{{ field.name }}}}" placeholder="{{{{ field.placeholder }}}}">{{{{ form_data.get(field.name, '') }}}}</textarea>
                {{% else %}}
                <input id="{{{{ field.name }}}}" type="{{{{ field.type }}}}" name="{{{{ field.name }}}}" value="{{{{ form_data.get(field.name, '') }}}}" placeholder="{{{{ field.placeholder }}}}" {{% if field.required %}}required{{% endif %}}>
                {{% endif %}}
            </div>
            {{% endfor %}}
        </div>
        <div class="button-row">
            <button class="button primary" type="submit">{{{{ submit_label }}}}</button>
            <a class="button secondary" href="/{resource_plural}">Back to table</a>
        </div>
    </form>
</section>
{{% endblock %}}
"""


def render_crud_detail_template(fields, resource_label, resource_plural):
    detail_rows = "".join([f"<li><strong>{field['label']}:</strong> {{{{ item.get('{field['name']}', '') }}}}</li>" for field in fields])
    return f"""{{% extends "base.html" %}}
{{% block content %}}
<section class="hero-card">
    <div>
        <p class="eyebrow">{resource_label} detail</p>
        <h2>{{{{ resource_label }}}} overview</h2>
        <ul>
            {detail_rows}
        </ul>
    </div>
    <div class="info-panel">
        <h3>Actions</h3>
        <div class="button-row">
            <a class="button primary" href="/{resource_plural}">Back to list</a>
            <a class="button secondary" href="/{resource_plural}/{{{{ item.id }}}}/edit">Edit</a>
        </div>
    </div>
</section>
{{% endblock %}}
"""


def render_style():
    return """
:root {
    --ink: #14213d;
    --teal: #0f6c7a;
    --sky: #eef6fb;
    --line: #d9e3ee;
    --card: #ffffff;
    --success: #e7f6ec;
    --error: #fde9e9;
}

* {
    box-sizing: border-box;
}

body {
    margin: 0;
    font-family: Arial, sans-serif;
    color: var(--ink);
    background: linear-gradient(180deg, #f7fbff 0%, #eef4fb 100%);
}

.app-header, .page-shell {
    max-width: 1080px;
    margin: 0 auto;
    padding-left: 24px;
    padding-right: 24px;
}

.app-header {
    padding-top: 32px;
    padding-bottom: 18px;
    display: flex;
    justify-content: space-between;
    gap: 18px;
    align-items: center;
}

.eyebrow {
    margin: 0;
    color: var(--teal);
    font-size: 12px;
    font-weight: bold;
    text-transform: uppercase;
    letter-spacing: 1px;
}

.subtitle {
    color: #536273;
}

.top-nav a {
    color: var(--ink);
    text-decoration: none;
    font-weight: bold;
}

.page-shell {
    padding-bottom: 48px;
}

.hero-card, .metric-card, .flash, form, .info-panel {
    background: var(--card);
    border-radius: 22px;
    box-shadow: 0 18px 48px rgba(20, 33, 61, 0.08);
}

.hero-card {
    display: grid;
    grid-template-columns: 1.2fr 0.8fr;
    gap: 18px;
    padding: 24px;
    margin-top: 18px;
}

.info-panel {
    padding: 20px;
}

.button-row {
    display: flex;
    flex-wrap: wrap;
    gap: 12px;
    margin-top: 18px;
}

.button {
    display: inline-block;
    padding: 12px 18px;
    border-radius: 999px;
    text-decoration: none;
    font-weight: bold;
}

.button.primary {
    background: var(--ink);
    color: white;
}

.button.secondary {
    background: #dceef1;
    color: var(--teal);
}

.flash-stack {
    display: grid;
    gap: 10px;
    margin-top: 8px;
}

.flash {
    padding: 14px 16px;
}

.flash-success {
    background: var(--success);
}

.flash-error {
    background: var(--error);
}

form {
    padding: 24px;
}

.form-grid {
    display: grid;
    grid-template-columns: repeat(2, minmax(0, 1fr));
    gap: 16px;
}

.field {
    margin-bottom: 8px;
}

.field.full {
    grid-column: 1 / -1;
}

label {
    display: block;
    font-weight: bold;
    margin-bottom: 6px;
    font-size: 13px;
}

input, textarea {
    width: 100%;
    padding: 12px 14px;
    border-radius: 14px;
    border: 1px solid var(--line);
    background: #fbfdff;
}

select {
    width: 100%;
    padding: 12px 14px;
    border-radius: 14px;
    border: 1px solid var(--line);
    background: #fbfdff;
}

textarea {
    min-height: 120px;
    resize: vertical;
}

.metric-grid {
    display: grid;
    grid-template-columns: repeat(3, minmax(0, 1fr));
    gap: 18px;
    margin-top: 18px;
}

.metric-card {
    padding: 22px;
}

.table {
    width: 100%;
    border-collapse: collapse;
}

.table th, .table td {
    text-align: left;
    padding: 12px 10px;
    border-bottom: 1px solid var(--line);
}

.link-button {
    background: none;
    border: none;
    color: var(--teal);
    cursor: pointer;
    padding: 0;
    font: inherit;
}

@media (max-width: 760px) {
    .hero-card, .metric-grid, .form-grid {
        grid-template-columns: 1fr;
    }
}
"""


def render_storage_service():
    return """import json
import os
import uuid
from datetime import datetime

DATA_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "app_data.json")


def _read():
    if not os.path.exists(DATA_PATH):
        return {"records": [], "items": {}}
    with open(DATA_PATH, "r", encoding="utf-8") as handle:
        return json.load(handle)


def _write(payload):
    with open(DATA_PATH, "w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2)


def append_record(category, data):
    payload = _read()
    payload.setdefault("records", []).append(
        {
            "category": category,
            "data": data,
            "timestamp": datetime.utcnow().isoformat(),
        }
    )
    _write(payload)


def list_items(resource):
    payload = _read()
    return payload.setdefault("items", {}).setdefault(resource, [])


def get_item(resource, item_id):
    items = list_items(resource)
    for item in items:
        if item.get("id") == item_id:
            return item
    return None


def create_item(resource, data):
    payload = _read()
    items = payload.setdefault("items", {}).setdefault(resource, [])
    record = dict(data)
    record["id"] = uuid.uuid4().hex[:8]
    record.setdefault("status", "active")
    record["created_at"] = datetime.utcnow().isoformat()
    items.append(record)
    _write(payload)
    return record


def update_item(resource, item_id, data):
    payload = _read()
    items = payload.setdefault("items", {}).setdefault(resource, [])
    for index, item in enumerate(items):
        if item.get("id") == item_id:
            updated = dict(item)
            updated.update(data)
            updated["id"] = item_id
            updated["updated_at"] = datetime.utcnow().isoformat()
            items[index] = updated
            _write(payload)
            return updated
    return None


def delete_item(resource, item_id):
    payload = _read()
    items = payload.setdefault("items", {}).setdefault(resource, [])
    payload["items"][resource] = [item for item in items if item.get("id") != item_id]
    _write(payload)


def seed_items(resource, rows):
    payload = _read()
    items = payload.setdefault("items", {}).setdefault(resource, [])
    if items:
        return
    for row in rows:
        record = dict(row)
        record["id"] = uuid.uuid4().hex[:8]
        record.setdefault("status", "active")
        record["created_at"] = datetime.utcnow().isoformat()
        items.append(record)
    _write(payload)


def build_dashboard_stats(resource=None):
    payload = _read()
    records = payload.get("records", [])
    categories = sorted({item["category"] for item in records})
    if resource:
        items = payload.get("items", {}).get(resource, [])
        active_items = len([item for item in items if str(item.get("status", "")).lower() == "active"])
        draft_items = len([item for item in items if str(item.get("status", "")).lower() == "draft"])
        return {
            "total_items": len(items),
            "active_items": active_items,
            "draft_items": draft_items,
            "last_updated": items[-1]["created_at"] if items else "No items yet",
        }
    return {
        "total_submissions": len(records),
        "module_count": len(categories),
        "categories": categories,
        "last_updated": records[-1]["timestamp"] if records else "No activity yet",
    }
"""


def render_config():
    return """import os


class Config:
    SECRET_KEY = os.environ.get("SECRET_KEY", "dev-secret-key")
"""


def render_app_py(context):
    module = context["module"]
    if module == "crud":
        return f"""from flask import Flask, render_template
from config import Config
from routes.auth import bp as auth_bp
from routes.crud import bp as crud_bp
from services.storage import seed_items


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    app.register_blueprint(auth_bp)
    app.register_blueprint(crud_bp)

    @app.route("/")
    def home():
        return render_template("home.html", page_title="Generated CRUD Home", description="Use the generated sign-in and CRUD flows to explore the starter.")

    seed_items("{context["resource_name"]}", [
        {{"name": "Starter record", "status": "active", "description": "Seeded demo item"}},
        {{"name": "Draft record", "status": "draft", "description": "Another seeded demo item"}},
    ])
    return app


app = create_app()


if __name__ == "__main__":
    app.run(debug=True)
"""
    dashboard_import = f"from routes.{module} import bp as module_bp\n"
    dashboard_route = ""
    if module != "dashboard":
        dashboard_route = """
    @app.route("/dashboard")
    def dashboard():
        stats = build_dashboard_stats()
        return render_template("dashboard.html", page_title="Project Dashboard", description="A lightweight operational view for the generated starter.", stats=stats)
"""
    return f"""from flask import Flask, render_template
from config import Config
from services.storage import build_dashboard_stats
{dashboard_import}


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    app.register_blueprint(module_bp)

    @app.route("/")
    def home():
        return render_template("home.html", page_title="Generated App Home", description="Use the generated module or dashboard to explore the flow.")
{dashboard_route}

    return app


app = create_app()


if __name__ == "__main__":
    app.run(debug=True)
"""


def render_tests(module):
    if module == "crud":
        return """from app import create_app


def test_home_page():
    app = create_app()
    client = app.test_client()
    response = client.get("/")
    assert response.status_code == 200


def test_login_page():
    app = create_app()
    client = app.test_client()
    response = client.get("/login")
    assert response.status_code == 200


def test_crud_redirect_when_logged_out():
    app = create_app()
    client = app.test_client()
    response = client.get("/resources")
    assert response.status_code == 302
"""
    return f"""from app import create_app


def test_home_page():
    app = create_app()
    client = app.test_client()
    response = client.get("/")
    assert response.status_code == 200


def test_module_page():
    app = create_app()
    client = app.test_client()
    response = client.get("/{module}")
    assert response.status_code == 200
"""


def render_readme(context):
    module_title = context["module"].replace("_", " ").title()
    roles = ", ".join(context.get("roles", [])) or "General user"
    workflows = ", ".join(context.get("workflows", [])) or "Standard form flow"
    constraints = ", ".join(context.get("constraints", [])) or "None explicitly parsed"
    return f"""# {context["title"]}

Generated with the AI Code Generator.

## Stack
- Framework: {context["framework"]}
- Language: {context["language"]}
- Module: {module_title}
- Storage: Local JSON file in `data/app_data.json`

## Prompt Analysis
- Intent: {context.get("intent", "data_collection")}
- Roles: {roles}
- Workflows: {workflows}
- Constraints: {constraints}
- Summary: {context.get("prompt_summary", "Not available")}

## Run
1. Create and activate a virtual environment.
2. Install dependencies with `pip install -r requirements.txt`.
3. Start the app with `python app.py`.
4. Open the local URL shown in the terminal.

## Demo
- Login credentials: `admin / admin123`
- Member credentials: `member / member123`
- Home page: `/`
- Module page: `/{context["resource_plural"] if context["module"] == "crud" else context["module"]}`
- Dashboard: `/dashboard`
"""


def render_setup_bat():
    return """@echo off
python -m venv .venv
call .venv\\Scripts\\activate
python -m pip install --upgrade pip
python -m pip install -r requirements.txt
python app.py
"""


def render_env_example():
    return """SECRET_KEY=change-me
"""


def render_quickstart():
    return """Quick start
1. Run `setup.bat` on Windows, or create a virtual environment manually.
2. Install dependencies from `requirements.txt`.
3. Start the app with `python app.py`.
4. Open the printed local URL in your browser.
"""


def render_auth_route():
    return """from flask import Blueprint, flash, redirect, render_template, request, session, url_for

bp = Blueprint("auth", __name__)

USERS = {
    "admin": {"password": "admin123", "role": "admin"},
    "member": {"password": "member123", "role": "member"},
}


@bp.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form.get("username", "").strip().lower()
        password = request.form.get("password", "").strip()
        user = USERS.get(username)
        if user and user["password"] == password:
            session["user"] = username
            session["role"] = user["role"]
            flash(f"Signed in as {user['role']}.", "success")
            return redirect(url_for("crud.dashboard"))
        flash("Invalid credentials. Use one of the seeded demo accounts.", "error")
    return render_template("login.html", page_title="Workspace Login", description="Use a demo account to enter the generated CRUD workspace.")


@bp.route("/logout")
def logout():
    session.clear()
    flash("Signed out.", "success")
    return redirect(url_for("auth.login"))
"""


def write_files(project_path, context, html_code, backend_code):
    module = context["module"]
    html_filename = f"{module}.html"
    if module == "crud":
        html_filename = f"{context['resource_name']}_overview.html"
    html_path = os.path.join(project_path, "templates", html_filename)
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html_code)

    route_path = os.path.join(project_path, "routes", f"{module}.py")
    with open(route_path, "w", encoding="utf-8") as f:
        f.write(backend_code)

    app_path = os.path.join(project_path, "app.py")
    with open(app_path, "w", encoding="utf-8") as f:
        f.write(render_app_py(context))

    config_path = os.path.join(project_path, "config.py")
    with open(config_path, "w", encoding="utf-8") as f:
        f.write(render_config())

    base_template_path = os.path.join(project_path, "templates", "base.html")
    with open(base_template_path, "w", encoding="utf-8") as f:
        f.write(render_base_template(context["title"]))

    home_template_path = os.path.join(project_path, "templates", "home.html")
    with open(home_template_path, "w", encoding="utf-8") as f:
        f.write(render_home_template(module, context["title"]))

    success_template_path = os.path.join(project_path, "templates", "success.html")
    with open(success_template_path, "w", encoding="utf-8") as f:
        f.write(render_success_template())

    dashboard_template_path = os.path.join(project_path, "templates", "dashboard.html")
    with open(dashboard_template_path, "w", encoding="utf-8") as f:
        if module == "crud":
            f.write(render_crud_dashboard_template(context["resource_name"].title()))
        else:
            f.write(render_dashboard_template())

    css_path = os.path.join(project_path, "static", "style.css")
    with open(css_path, "w", encoding="utf-8") as f:
        f.write(render_style())

    storage_path = os.path.join(project_path, "services", "storage.py")
    with open(storage_path, "w", encoding="utf-8") as f:
        f.write(render_storage_service())

    requirements_path = os.path.join(project_path, "requirements.txt")
    with open(requirements_path, "w", encoding="utf-8") as f:
        f.write("flask\n")

    readme_path = os.path.join(project_path, "README.md")
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(render_readme(context))

    setup_path = os.path.join(project_path, "setup.bat")
    with open(setup_path, "w", encoding="utf-8") as f:
        f.write(render_setup_bat())

    env_path = os.path.join(project_path, ".env.example")
    with open(env_path, "w", encoding="utf-8") as f:
        f.write(render_env_example())

    quickstart_path = os.path.join(project_path, "QUICKSTART.txt")
    with open(quickstart_path, "w", encoding="utf-8") as f:
        f.write(render_quickstart())

    tests_path = os.path.join(project_path, "tests", "test_app.py")
    with open(tests_path, "w", encoding="utf-8") as f:
        f.write(render_tests(module))

    data_path = os.path.join(project_path, "data", "app_data.json")
    with open(data_path, "w", encoding="utf-8") as f:
        json.dump({"records": [], "items": {}}, f, indent=2)

    if module == "crud":
        auth_route_path = os.path.join(project_path, "routes", "auth.py")
        with open(auth_route_path, "w", encoding="utf-8") as f:
            f.write(render_auth_route())

        resource = context["resource_name"]
        list_path = os.path.join(project_path, "templates", f"{resource}_list.html")
        with open(list_path, "w", encoding="utf-8") as f:
            f.write(render_crud_list_template(context["field_schema"], resource.title(), context["resource_plural"]))

        form_path = os.path.join(project_path, "templates", f"{resource}_form.html")
        with open(form_path, "w", encoding="utf-8") as f:
            f.write(render_crud_form_template(resource.title(), context["resource_plural"]))

        detail_path = os.path.join(project_path, "templates", f"{resource}_detail.html")
        with open(detail_path, "w", encoding="utf-8") as f:
            f.write(render_crud_detail_template(context["field_schema"], resource.title(), context["resource_plural"]))

        login_path = os.path.join(project_path, "templates", "login.html")
        with open(login_path, "w", encoding="utf-8") as f:
            f.write(render_crud_login_template())

    return project_path


def generate_project(context, html_code, backend_code):
    project_path = create_project_structure(context["project_name"])
    write_files(project_path, context, html_code, backend_code)
    return project_path
