import os
import json

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "generated_projects"))


def create_project_structure(project_name):
    project_path = os.path.join(BASE_DIR, project_name)
    templates_path = os.path.join(project_path, "templates")
    routes_path = os.path.join(project_path, "routes")
    static_path = os.path.join(project_path, "static")
    services_path = os.path.join(project_path, "services")
    tests_path = os.path.join(project_path, "tests")
    data_path = os.path.join(project_path, "data")

    os.makedirs(project_path, exist_ok=True)
    os.makedirs(templates_path, exist_ok=True)
    os.makedirs(routes_path, exist_ok=True)
    os.makedirs(static_path, exist_ok=True)
    os.makedirs(services_path, exist_ok=True)
    os.makedirs(tests_path, exist_ok=True)
    os.makedirs(data_path, exist_ok=True)

    for package_path in (routes_path, services_path):
        init_path = os.path.join(package_path, "__init__.py")
        with open(init_path, "w") as f:
            f.write("")

    return project_path


def render_base_template(project_title):
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{{{ page_title or "{project_title}" }}}}</title>
    <link rel="stylesheet" href="{{{{ url_for('static', filename='style.css') }}}}">
</head>
<body>
    <header class="app-header">
        <div>
            <p class="eyebrow">{project_title}</p>
            <h1>{{{{ page_title or "{project_title}" }}}}</h1>
            <p class="subtitle">{{{{ description or "Generated by the AI Code Generator." }}}}</p>
        </div>
        <nav class="top-nav">
            <a href="{{{{ url_for('home') }}}}">Home</a>
        </nav>
    </header>
    <main class="page-shell">
        {{% with messages = get_flashed_messages(with_categories=true) %}}
            {{% if messages %}}
                <section class="flash-stack">
                {{% for category, message in messages %}}
                    <div class="flash {{'flash-success' if category == 'success' else 'flash-error'}}">{{{{ message }}}}</div>
                {{% endfor %}}
                </section>
            {{% endif %}}
        {{% endwith %}}
        {{% block content %}}{{% endblock %}}
    </main>
</body>
</html>
"""


def render_home_template(module, project_title):
    if module == "workflow":
        return """{% extends "base.html" %}
{% block content %}
<section class="hero-card">
    <div>
        <p class="eyebrow">Generated workflow app</p>
        <h2>Integrated multi-step starter</h2>
        <p>This starter combines registration, login, dashboard, and additional workflow modules into one Flask app.</p>
        <div class="button-row">
            <a class="button primary" href="/registration">Start workflow</a>
            <a class="button secondary" href="/login">Open login</a>
        </div>
    </div>
    <div class="info-panel">
        <h3>What is included</h3>
        <ul>
            <li>Shared auth and session flow</li>
            <li>Redirects between workflow pages</li>
            <li>Common storage for users and submissions</li>
            <li>Dashboard summary for the whole workflow</li>
        </ul>
    </div>
</section>
{% endblock %}
"""
    if module in {"crud", "inventory_management", "employee_management", "customer_management", "ticket_system", "task_manager", "product_catalog"}:
        return """{% extends "base.html" %}
{% block content %}
<section class="hero-card">
    <div>
        <p class="eyebrow">Generated CRUD workspace</p>
        <h2>Role-based resource management starter</h2>
        <p>This starter includes sign-in, dashboard metrics, resource list/search, create/edit pages, detail views, and protected destructive actions.</p>
        <div class="button-row">
            <a class="button primary" href="/login">Open login</a>
            <a class="button secondary" href="/dashboard">Open dashboard</a>
        </div>
    </div>
    <div class="info-panel">
        <h3>Default roles</h3>
        <ul>
            <li>Admin: full create, edit, delete access</li>
            <li>Member: read-only access to list and detail pages</li>
            <li>Seeded demo data appears automatically on first run</li>
            <li>Storage backend is selected during generation</li>
        </ul>
    </div>
</section>
{% endblock %}
"""
    module_title = module.replace("_", " ").title()
    return f"""{{% extends "base.html" %}}
{{% block content %}}
<section class="hero-card">
    <div>
        <p class="eyebrow">Generated project</p>
        <h2>{module_title} module ready</h2>
        <p>This starter includes routes, persistence helpers, a success path, a dashboard summary, tests, and a README.</p>
        <div class="button-row">
            <a class="button primary" href="/{module}">Open module</a>
            <a class="button secondary" href="/dashboard">View dashboard</a>
        </div>
    </div>
    <div class="info-panel">
        <h3>What is included</h3>
        <ul>
            <li>Server-side validation</li>
            <li>Generated storage service for JSON or SQLite</li>
            <li>Companion templates and styling</li>
            <li>Smoke tests and setup instructions</li>
        </ul>
    </div>
</section>
{{% endblock %}}
"""


def render_success_template():
    return """{% extends "base.html" %}
{% block content %}
<section class="hero-card">
    <div>
        <p class="eyebrow">Submission captured</p>
        <h2>{{ module_name }} completed successfully</h2>
        <p>The generated flow stored the submitted payload in the local JSON data store.</p>
        <div class="button-row">
            <a class="button primary" href="{{ url_for('home') }}">Back home</a>
            <a class="button secondary" href="/dashboard">Open dashboard</a>
        </div>
    </div>
    <div class="info-panel">
        <h3>Quick stats</h3>
        <ul>
            <li>Total submissions: {{ stats.total_submissions }}</li>
            <li>Active modules: {{ stats.module_count }}</li>
            <li>Stored categories: {{ stats.categories|join(', ') if stats.categories else 'None yet' }}</li>
        </ul>
    </div>
</section>
{% endblock %}
"""


def render_dashboard_template(storage_label):
    return f"""{{% extends "base.html" %}}
{{% block content %}}
<section class="metric-grid">
    <article class="metric-card">
        <p>Total submissions</p>
        <h2>{{{{ stats.total_submissions }}}}</h2>
    </article>
    <article class="metric-card">
        <p>Active modules</p>
        <h2>{{{{ stats.module_count }}}}</h2>
    </article>
    <article class="metric-card">
        <p>Last updated</p>
        <h2>{{{{ stats.last_updated }}}}</h2>
    </article>
</section>
<section class="hero-card">
    <div>
        <h3>Recent categories</h3>
        <ul>
            {{% for category in stats.categories %}}
            <li>{{{{ category }}}}</li>
            {{% else %}}
            <li>No submissions stored yet.</li>
            {{% endfor %}}
        </ul>
    </div>
    <div class="info-panel">
        <h3>Storage</h3>
        <p>Data is stored locally using <code>{storage_label}</code> for easy inspection during development.</p>
    </div>
</section>
{{% endblock %}}
"""


def render_workflow_dashboard_template(module_labels):
    links = "".join([f'<li><a href="/{module}">{label}</a></li>' for module, label in module_labels])
    return f"""{{% extends "base.html" %}}
{{% block content %}}
<section class="metric-grid">
    <article class="metric-card">
        <p>Total users</p>
        <h2>{{{{ stats.total_users }}}}</h2>
    </article>
    <article class="metric-card">
        <p>Total submissions</p>
        <h2>{{{{ stats.total_submissions }}}}</h2>
    </article>
    <article class="metric-card">
        <p>Active modules</p>
        <h2>{{{{ stats.module_count }}}}</h2>
    </article>
</section>
<section class="hero-card">
    <div>
        <h3>Workflow modules</h3>
        <ul>
            {links}
        </ul>
    </div>
    <div class="info-panel">
        <h3>Recent activity</h3>
        <ul>
            {{% for entry in recent_entries %}}
            <li>{{{{ entry.category }}}}: {{{{ entry.timestamp }}}}</li>
            {{% else %}}
            <li>No workflow submissions yet.</li>
            {{% endfor %}}
        </ul>
    </div>
</section>
{{% endblock %}}
"""


def render_workflow_form_template(module, page_title, description, fields, submit_label):
    body = []
    for field in fields:
        if field["type"] == "textarea":
            body.append(
                f"""            <div class="field full">
                <label for="{field["name"]}">{field["label"]}</label>
                <textarea id="{field["name"]}" name="{field["name"]}" placeholder="{field["placeholder"]}">{{{{ form_data.get('{field["name"]}', '') }}}}</textarea>
            </div>"""
            )
        else:
            required = "required" if field["required"] else ""
            body.append(
                f"""            <div class="field">
                <label for="{field["name"]}">{field["label"]}</label>
                <input id="{field["name"]}" type="{field["type"]}" name="{field["name"]}" value="{{{{ form_data.get('{field["name"]}', '') }}}}" placeholder="{field["placeholder"]}" {required}>
            </div>"""
            )
    field_markup = "\n".join(body)
    return f"""{{% extends "base.html" %}}
{{% block content %}}
<section class="hero-card">
    <div>
        <p class="eyebrow">Workflow module</p>
        <h2>{page_title}</h2>
        <p>{description}</p>
    </div>
    <form method="POST" action="/{module}">
        <div class="form-grid">
{field_markup}
        </div>
        <div class="button-row">
            <button class="button primary" type="submit">{submit_label}</button>
            <a class="button secondary" href="/dashboard">Back to dashboard</a>
        </div>
    </form>
</section>
{{% endblock %}}
"""


def render_workflow_login_template():
    return """{% extends "base.html" %}
{% block content %}
<section class="hero-card">
    <div>
        <p class="eyebrow">Workflow auth</p>
        <h2>Sign in to continue</h2>
        <p>Use the registration step or sign in with a previously created account.</p>
    </div>
    <form method="POST" action="/login">
        <div class="form-grid">
            <div class="field">
                <label for="username">Username</label>
                <input id="username" name="username" type="text" required>
            </div>
            <div class="field">
                <label for="password">Password</label>
                <input id="password" name="password" type="password" required>
            </div>
        </div>
        <div class="button-row">
            <button class="button primary" type="submit">Sign in</button>
            <a class="button secondary" href="/registration">Create account</a>
        </div>
    </form>
</section>
{% endblock %}
"""


def render_crud_dashboard_template(resource_label, storage_label):
    return f"""{{% extends "base.html" %}}
{{% block content %}}
<section class="metric-grid">
    {{% for card in dashboard_cards %}}
    <article class="metric-card">
        <p>{{{{ card.label }}}}</p>
        <h2>{{{{ card.value }}}}</h2>
    </article>
    {{% endfor %}}
</section>
<section class="hero-card">
    <div>
        <h3>Management actions</h3>
        <ul>
            <li><a href="/{{{{ resource_plural }}}}">Open table view</a></li>
            <li><a href="/{{{{ resource_plural }}}}/new">Create a new {resource_label.lower()}</a></li>
            <li>Use search and list filters from the table screen</li>
        </ul>
    </div>
    <div class="info-panel">
        <h3>Access summary</h3>
        <p>Signed in as <strong>{{{{ current_role }}}}</strong>. Admin users can create, edit, and delete records.</p>
        <p>Storage backend: <code>{storage_label}</code></p>
        {{% if facet_summary and facet_summary["values"] %}}
        <h3>{{{{ facet_summary["field"].replace('_', ' ').title() }}}} breakdown</h3>
        <ul>
            {{% for item in facet_summary["values"] %}}
            <li>{{{{ item.label }}}}: {{{{ item.count }}}}</li>
            {{% endfor %}}
        </ul>
        {{% endif %}}
    </div>
</section>
{{% endblock %}}
"""


def render_crud_login_template():
    return """{% extends "base.html" %}
{% block content %}
<section class="hero-card">
    <div>
        <p class="eyebrow">Role-based auth</p>
        <h2>Sign in to the generated workspace</h2>
        <p>Use one of the seeded demo accounts to explore the CRUD workflow.</p>
        <ul>
            <li>Admin: <code>admin / admin123</code></li>
            <li>Member: <code>member / member123</code></li>
        </ul>
    </div>
    <form method="POST">
        <div class="field">
            <label for="username">Username</label>
            <input id="username" name="username" type="text" required>
        </div>
        <div class="field">
            <label for="password">Password</label>
            <input id="password" name="password" type="password" required>
        </div>
        <button class="button primary" type="submit">Sign in</button>
    </form>
</section>
{% endblock %}
"""


def render_crud_list_template(fields, resource_label, resource_plural, filter_fields):
    searchable_columns = "".join([f"<th>{field['label']}</th>" for field in fields[:4]])
    row_values = "".join([f"<td>{{{{ item.get('{field['name']}', '') }}}}</td>" for field in fields[:4]])
    filter_markup = ""
    for filter_field in filter_fields:
        label = filter_field.replace("_", " ").title()
        filter_markup += f"""
            <div class="field">
                <label for="{filter_field}">{label}</label>
                <input id="{filter_field}" name="{filter_field}" type="text" value="{{{{ active_filters.get('{filter_field}', '') }}}}" placeholder="Filter by {label.lower()}">
            </div>"""
    return f"""{{% extends "base.html" %}}
{{% block content %}}
<section class="hero-card">
    <div>
        <p class="eyebrow">{resource_label} management</p>
        <h2>{{{{ resource_label }}}} table</h2>
        <p>Search, filter, inspect, and manage records from one place.</p>
    </div>
    <form method="GET" action="/{resource_plural}">
        <div class="form-grid">
            <div class="field">
                <label for="q">Search</label>
                <input id="q" name="q" type="text" value="{{{{ query }}}}" placeholder="Search records">
            </div>
{filter_markup}
        </div>
        <div class="button-row">
            <button class="button primary" type="submit">Apply filters</button>
            {{% if role == "admin" %}}<a class="button secondary" href="/{resource_plural}/new">Create {resource_label}</a>{{% endif %}}
        </div>
    </form>
</section>
<section class="hero-card">
    <div style="grid-column: 1 / -1;">
        <table class="table">
            <thead>
                <tr>
                    {searchable_columns}
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {{% for item in items %}}
                <tr>
                    {row_values}
                    <td>
                        <a href="/{resource_plural}/{{{{ item.id }}}}">View</a>
                        {{% if role == "admin" %}}
                        <a href="/{resource_plural}/{{{{ item.id }}}}/edit">Edit</a>
                        <form method="POST" action="/{resource_plural}/{{{{ item.id }}}}/delete" style="display:inline;">
                            <button type="submit" class="link-button">Delete</button>
                        </form>
                        {{% endif %}}
                    </td>
                </tr>
                {{% else %}}
                <tr>
                    <td colspan="{len(fields[:4]) + 1}">No records matched the current filters.</td>
                </tr>
                {{% endfor %}}
            </tbody>
        </table>
    </div>
</section>
{{% endblock %}}
"""


def render_crud_form_template(resource_label, resource_plural):
    return f"""{{% extends "base.html" %}}
{{% block content %}}
<section class="hero-card">
    <div>
        <p class="eyebrow">{resource_label} workflow</p>
        <h2>{{{{ page_title }}}}</h2>
        <p>Capture and validate core record details for this generated CRUD module.</p>
    </div>
    <form method="POST" action="{{{{ action_url }}}}">
        <div class="form-grid">
            {{% for field in fields %}}
            <div class="field {{% if field.type == 'textarea' %}}full{{% endif %}}">
                <label for="{{{{ field.name }}}}">{{{{ field.label }}}}</label>
                {{% if field.type == "textarea" %}}
                <textarea id="{{{{ field.name }}}}" name="{{{{ field.name }}}}" placeholder="{{{{ field.placeholder }}}}">{{{{ form_data.get(field.name, '') }}}}</textarea>
                {{% else %}}
                <input id="{{{{ field.name }}}}" type="{{{{ field.type }}}}" name="{{{{ field.name }}}}" value="{{{{ form_data.get(field.name, '') }}}}" placeholder="{{{{ field.placeholder }}}}" {{% if field.required %}}required{{% endif %}}>
                {{% endif %}}
            </div>
            {{% endfor %}}
        </div>
        <div class="button-row">
            <button class="button primary" type="submit">{{{{ submit_label }}}}</button>
            <a class="button secondary" href="/{resource_plural}">Back to table</a>
        </div>
    </form>
</section>
{{% endblock %}}
"""


def render_crud_detail_template(fields, resource_label, resource_plural):
    detail_rows = "".join([f"<li><strong>{field['label']}:</strong> {{{{ item.get('{field['name']}', '') }}}}</li>" for field in fields])
    return f"""{{% extends "base.html" %}}
{{% block content %}}
<section class="hero-card">
    <div>
        <p class="eyebrow">{resource_label} detail</p>
        <h2>{{{{ resource_label }}}} overview</h2>
        <ul>
            {detail_rows}
        </ul>
    </div>
    <div class="info-panel">
        <h3>Actions</h3>
        <div class="button-row">
            <a class="button primary" href="/{resource_plural}">Back to list</a>
            <a class="button secondary" href="/{resource_plural}/{{{{ item.id }}}}/edit">Edit</a>
        </div>
    </div>
</section>
{{% endblock %}}
"""


def render_style():
    return """
:root {
    --ink: #14213d;
    --teal: #0f6c7a;
    --sky: #eef6fb;
    --line: #d9e3ee;
    --card: #ffffff;
    --success: #e7f6ec;
    --error: #fde9e9;
}

* {
    box-sizing: border-box;
}

body {
    margin: 0;
    font-family: Arial, sans-serif;
    color: var(--ink);
    background: linear-gradient(180deg, #f7fbff 0%, #eef4fb 100%);
}

.app-header, .page-shell {
    max-width: 1080px;
    margin: 0 auto;
    padding-left: 24px;
    padding-right: 24px;
}

.app-header {
    padding-top: 32px;
    padding-bottom: 18px;
    display: flex;
    justify-content: space-between;
    gap: 18px;
    align-items: center;
}

.eyebrow {
    margin: 0;
    color: var(--teal);
    font-size: 12px;
    font-weight: bold;
    text-transform: uppercase;
    letter-spacing: 1px;
}

.subtitle {
    color: #536273;
}

.top-nav a {
    color: var(--ink);
    text-decoration: none;
    font-weight: bold;
}

.page-shell {
    padding-bottom: 48px;
}

.hero-card, .metric-card, .flash, form, .info-panel {
    background: var(--card);
    border-radius: 22px;
    box-shadow: 0 18px 48px rgba(20, 33, 61, 0.08);
}

.hero-card {
    display: grid;
    grid-template-columns: 1.2fr 0.8fr;
    gap: 18px;
    padding: 24px;
    margin-top: 18px;
}

.info-panel {
    padding: 20px;
}

.button-row {
    display: flex;
    flex-wrap: wrap;
    gap: 12px;
    margin-top: 18px;
}

.button {
    display: inline-block;
    padding: 12px 18px;
    border-radius: 999px;
    text-decoration: none;
    font-weight: bold;
}

.button.primary {
    background: var(--ink);
    color: white;
}

.button.secondary {
    background: #dceef1;
    color: var(--teal);
}

.flash-stack {
    display: grid;
    gap: 10px;
    margin-top: 8px;
}

.flash {
    padding: 14px 16px;
}

.flash-success {
    background: var(--success);
}

.flash-error {
    background: var(--error);
}

form {
    padding: 24px;
}

.form-grid {
    display: grid;
    grid-template-columns: repeat(2, minmax(0, 1fr));
    gap: 16px;
}

.field {
    margin-bottom: 8px;
}

.field.full {
    grid-column: 1 / -1;
}

label {
    display: block;
    font-weight: bold;
    margin-bottom: 6px;
    font-size: 13px;
}

input, textarea {
    width: 100%;
    padding: 12px 14px;
    border-radius: 14px;
    border: 1px solid var(--line);
    background: #fbfdff;
}

select {
    width: 100%;
    padding: 12px 14px;
    border-radius: 14px;
    border: 1px solid var(--line);
    background: #fbfdff;
}

textarea {
    min-height: 120px;
    resize: vertical;
}

.metric-grid {
    display: grid;
    grid-template-columns: repeat(3, minmax(0, 1fr));
    gap: 18px;
    margin-top: 18px;
}

.metric-card {
    padding: 22px;
}

.table {
    width: 100%;
    border-collapse: collapse;
}

.table th, .table td {
    text-align: left;
    padding: 12px 10px;
    border-bottom: 1px solid var(--line);
}

.link-button {
    background: none;
    border: none;
    color: var(--teal);
    cursor: pointer;
    padding: 0;
    font: inherit;
}

@media (max-width: 760px) {
    .hero-card, .metric-grid, .form-grid {
        grid-template-columns: 1fr;
    }
}
"""


def render_json_storage_service():
    return """import json
import os
import uuid
from datetime import datetime

DATA_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "app_data.json")


def init_storage():
    os.makedirs(os.path.dirname(DATA_PATH), exist_ok=True)
    if not os.path.exists(DATA_PATH):
        with open(DATA_PATH, "w", encoding="utf-8") as handle:
            json.dump({"records": [], "items": {}}, handle, indent=2)


def _read():
    init_storage()
    if not os.path.exists(DATA_PATH):
        return {"records": [], "items": {}}
    with open(DATA_PATH, "r", encoding="utf-8") as handle:
        return json.load(handle)


def _write(payload):
    with open(DATA_PATH, "w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2)


def append_record(category, data):
    payload = _read()
    payload.setdefault("records", []).append(
        {
            "category": category,
            "data": data,
            "timestamp": datetime.utcnow().isoformat(),
        }
    )
    _write(payload)


def list_records(category=None):
    payload = _read()
    records = payload.get("records", [])
    if category:
        records = [record for record in records if record.get("category") == category]
    return list(reversed(records))


def create_user(data):
    payload = _read()
    users = payload.setdefault("users", [])
    record = dict(data)
    record["id"] = uuid.uuid4().hex[:8]
    record.setdefault("role", "member")
    record["created_at"] = datetime.utcnow().isoformat()
    users.append(record)
    _write(payload)
    return record


def get_user_by_username(username):
    payload = _read()
    for user in payload.setdefault("users", []):
        if user.get("username", "").lower() == str(username).lower():
            return user
    return None


def update_user_profile(username, updates):
    payload = _read()
    users = payload.setdefault("users", [])
    for index, user in enumerate(users):
        if user.get("username", "").lower() == str(username).lower():
            updated = dict(user)
            updated.update(updates)
            updated["updated_at"] = datetime.utcnow().isoformat()
            users[index] = updated
            _write(payload)
            return updated
    return None


def list_items(resource):
    payload = _read()
    return payload.setdefault("items", {}).setdefault(resource, [])


def get_item(resource, item_id):
    items = list_items(resource)
    for item in items:
        if item.get("id") == item_id:
            return item
    return None


def create_item(resource, data):
    payload = _read()
    items = payload.setdefault("items", {}).setdefault(resource, [])
    record = dict(data)
    record["id"] = uuid.uuid4().hex[:8]
    record.setdefault("status", "active")
    record["created_at"] = datetime.utcnow().isoformat()
    items.append(record)
    _write(payload)
    return record


def update_item(resource, item_id, data):
    payload = _read()
    items = payload.setdefault("items", {}).setdefault(resource, [])
    for index, item in enumerate(items):
        if item.get("id") == item_id:
            updated = dict(item)
            updated.update(data)
            updated["id"] = item_id
            updated["updated_at"] = datetime.utcnow().isoformat()
            items[index] = updated
            _write(payload)
            return updated
    return None


def delete_item(resource, item_id):
    payload = _read()
    items = payload.setdefault("items", {}).setdefault(resource, [])
    payload["items"][resource] = [item for item in items if item.get("id") != item_id]
    _write(payload)


def seed_items(resource, rows):
    payload = _read()
    items = payload.setdefault("items", {}).setdefault(resource, [])
    if items:
        return
    for row in rows:
        record = dict(row)
        record["id"] = uuid.uuid4().hex[:8]
        record.setdefault("status", "active")
        record["created_at"] = datetime.utcnow().isoformat()
        items.append(record)
    _write(payload)


def build_dashboard_stats(resource=None):
    payload = _read()
    records = payload.get("records", [])
    categories = sorted({item["category"] for item in records})
    if resource:
        items = payload.get("items", {}).get(resource, [])
        active_items = len([item for item in items if str(item.get("status", "")).lower() == "active"])
        draft_items = len([item for item in items if str(item.get("status", "")).lower() == "draft"])
        return {
            "total_items": len(items),
            "active_items": active_items,
            "draft_items": draft_items,
            "last_updated": items[-1]["created_at"] if items else "No items yet",
        }
    return {
        "total_submissions": len(records),
        "module_count": len(categories),
        "categories": categories,
        "last_updated": records[-1]["timestamp"] if records else "No activity yet",
        "total_users": len(payload.get("users", [])),
    }
"""


def render_sqlite_storage_service():
    return """import json
import os
import sqlite3
import uuid
from datetime import datetime

DB_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "app_data.sqlite3")


def _connect():
    connection = sqlite3.connect(DB_PATH)
    connection.row_factory = sqlite3.Row
    connection.execute("PRAGMA journal_mode=OFF")
    return connection


def init_storage():
    connection = _connect()
    cursor = connection.cursor()
    cursor.execute(
        '''
        CREATE TABLE IF NOT EXISTS generic_records (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            category TEXT NOT NULL,
            data TEXT NOT NULL,
            timestamp TEXT NOT NULL
        )
        '''
    )
    cursor.execute(
        '''
        CREATE TABLE IF NOT EXISTS resource_items (
            id TEXT PRIMARY KEY,
            resource TEXT NOT NULL,
            data TEXT NOT NULL,
            status TEXT,
            created_at TEXT NOT NULL,
            updated_at TEXT
        )
        '''
    )
    cursor.execute(
        '''
        CREATE TABLE IF NOT EXISTS users (
            id TEXT PRIMARY KEY,
            username TEXT UNIQUE NOT NULL,
            password TEXT NOT NULL,
            role TEXT NOT NULL,
            data TEXT NOT NULL,
            created_at TEXT NOT NULL,
            updated_at TEXT
        )
        '''
    )
    connection.commit()
    connection.close()


def append_record(category, data):
    init_storage()
    connection = _connect()
    connection.execute(
        "INSERT INTO generic_records (category, data, timestamp) VALUES (?, ?, ?)",
        (category, json.dumps(data), datetime.utcnow().isoformat()),
    )
    connection.commit()
    connection.close()


def list_records(category=None):
    init_storage()
    connection = _connect()
    if category:
        rows = connection.execute(
            "SELECT category, data, timestamp FROM generic_records WHERE category = ? ORDER BY timestamp DESC",
            (category,),
        ).fetchall()
    else:
        rows = connection.execute(
            "SELECT category, data, timestamp FROM generic_records ORDER BY timestamp DESC"
        ).fetchall()
    connection.close()
    return [{"category": row["category"], "data": json.loads(row["data"]), "timestamp": row["timestamp"]} for row in rows]


def create_user(data):
    init_storage()
    user_id = uuid.uuid4().hex[:8]
    record = dict(data)
    record.setdefault("role", "member")
    created_at = datetime.utcnow().isoformat()
    connection = _connect()
    connection.execute(
        "INSERT INTO users (id, username, password, role, data, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)",
        (
            user_id,
            record.get("username", ""),
            record.get("password", ""),
            record.get("role", "member"),
            json.dumps(record),
            created_at,
            None,
        ),
    )
    connection.commit()
    connection.close()
    record["id"] = user_id
    record["created_at"] = created_at
    return record


def get_user_by_username(username):
    init_storage()
    connection = _connect()
    row = connection.execute(
        "SELECT id, username, password, role, data, created_at, updated_at FROM users WHERE lower(username) = lower(?)",
        (username,),
    ).fetchone()
    connection.close()
    if not row:
        return None
    payload = json.loads(row["data"])
    payload["id"] = row["id"]
    payload["username"] = row["username"]
    payload["password"] = row["password"]
    payload["role"] = row["role"]
    payload["created_at"] = row["created_at"]
    if row["updated_at"]:
        payload["updated_at"] = row["updated_at"]
    return payload


def update_user_profile(username, updates):
    init_storage()
    user = get_user_by_username(username)
    if not user:
        return None
    updated = dict(user)
    updated.update(updates)
    updated_at = datetime.utcnow().isoformat()
    connection = _connect()
    connection.execute(
        "UPDATE users SET data = ?, role = ?, updated_at = ? WHERE lower(username) = lower(?)",
        (json.dumps(updated), updated.get("role", "member"), updated_at, username),
    )
    connection.commit()
    connection.close()
    updated["updated_at"] = updated_at
    return updated


def _row_to_item(row):
    payload = json.loads(row["data"])
    payload["id"] = row["id"]
    payload["status"] = row["status"] or payload.get("status", "")
    payload["created_at"] = row["created_at"]
    if row["updated_at"]:
        payload["updated_at"] = row["updated_at"]
    return payload


def list_items(resource):
    init_storage()
    connection = _connect()
    rows = connection.execute(
        "SELECT id, data, status, created_at, updated_at FROM resource_items WHERE resource = ? ORDER BY created_at DESC",
        (resource,),
    ).fetchall()
    connection.close()
    return [_row_to_item(row) for row in rows]


def get_item(resource, item_id):
    init_storage()
    connection = _connect()
    row = connection.execute(
        "SELECT id, data, status, created_at, updated_at FROM resource_items WHERE resource = ? AND id = ?",
        (resource, item_id),
    ).fetchone()
    connection.close()
    return _row_to_item(row) if row else None


def create_item(resource, data):
    init_storage()
    item_id = uuid.uuid4().hex[:8]
    record = dict(data)
    record.setdefault("status", "active")
    created_at = datetime.utcnow().isoformat()
    connection = _connect()
    connection.execute(
        "INSERT INTO resource_items (id, resource, data, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)",
        (item_id, resource, json.dumps(record), record.get("status", "active"), created_at, None),
    )
    connection.commit()
    connection.close()
    record["id"] = item_id
    record["created_at"] = created_at
    return record


def update_item(resource, item_id, data):
    init_storage()
    existing = get_item(resource, item_id)
    if not existing:
        return None
    updated = dict(existing)
    updated.update(data)
    updated["id"] = item_id
    updated_at = datetime.utcnow().isoformat()
    connection = _connect()
    connection.execute(
        "UPDATE resource_items SET data = ?, status = ?, updated_at = ? WHERE resource = ? AND id = ?",
        (json.dumps(updated), updated.get("status", ""), updated_at, resource, item_id),
    )
    connection.commit()
    connection.close()
    updated["updated_at"] = updated_at
    return updated


def delete_item(resource, item_id):
    init_storage()
    connection = _connect()
    connection.execute(
        "DELETE FROM resource_items WHERE resource = ? AND id = ?",
        (resource, item_id),
    )
    connection.commit()
    connection.close()


def seed_items(resource, rows):
    init_storage()
    connection = _connect()
    count = connection.execute(
        "SELECT COUNT(*) AS count FROM resource_items WHERE resource = ?",
        (resource,),
    ).fetchone()["count"]
    if count:
        connection.close()
        return
    for row in rows:
        item_id = uuid.uuid4().hex[:8]
        record = dict(row)
        record.setdefault("status", "active")
        created_at = datetime.utcnow().isoformat()
        connection.execute(
            "INSERT INTO resource_items (id, resource, data, status, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)",
            (item_id, resource, json.dumps(record), record.get("status", "active"), created_at, None),
        )
    connection.commit()
    connection.close()


def build_dashboard_stats(resource=None):
    init_storage()
    connection = _connect()
    if resource:
        rows = connection.execute(
            "SELECT status, created_at FROM resource_items WHERE resource = ? ORDER BY created_at DESC",
            (resource,),
        ).fetchall()
        connection.close()
        active_items = len([row for row in rows if str(row["status"]).lower() == "active"])
        draft_items = len([row for row in rows if str(row["status"]).lower() == "draft"])
        return {
            "total_items": len(rows),
            "active_items": active_items,
            "draft_items": draft_items,
            "last_updated": rows[0]["created_at"] if rows else "No items yet",
        }
    rows = connection.execute(
        "SELECT category, timestamp FROM generic_records ORDER BY timestamp DESC"
    ).fetchall()
    user_count = connection.execute("SELECT COUNT(*) AS count FROM users").fetchone()["count"]
    connection.close()
    categories = sorted({row["category"] for row in rows})
    return {
        "total_submissions": len(rows),
        "module_count": len(categories),
        "categories": categories,
        "last_updated": rows[0]["timestamp"] if rows else "No activity yet",
        "total_users": user_count,
    }
"""


def render_config():
    return """import os


class Config:
    SECRET_KEY = os.environ.get("SECRET_KEY", "dev-secret-key")
"""


def render_app_py(context):
    module = context["module"]
    if context.get("app_family") == "workflow":
        return """import os

from flask import Flask, render_template
from config import Config
from routes.workflow import bp as workflow_bp
from services.storage import init_storage

BASE_DIR = os.path.dirname(__file__)


def create_app():
    app = Flask(
        __name__,
        template_folder=os.path.join(BASE_DIR, "templates"),
        static_folder=os.path.join(BASE_DIR, "static"),
    )
    app.config.from_object(Config)
    app.register_blueprint(workflow_bp)
    init_storage()

    @app.route("/")
    def home():
        return render_template("home.html", page_title="Generated Workflow Home", description="Start with registration or sign in to continue through the generated workflow.")

    return app


app = create_app()


if __name__ == "__main__":
    app.run(debug=True)
"""
    if context.get("app_family") == "crud":
        return f"""import os

from flask import Flask, render_template
from config import Config
from routes.auth import bp as auth_bp
from routes.{module} import bp as crud_bp
from services.storage import init_storage, seed_items

BASE_DIR = os.path.dirname(__file__)


def create_app():
    app = Flask(
        __name__,
        template_folder=os.path.join(BASE_DIR, "templates"),
        static_folder=os.path.join(BASE_DIR, "static"),
    )
    app.config.from_object(Config)
    app.register_blueprint(auth_bp)
    app.register_blueprint(crud_bp)
    init_storage()

    @app.route("/")
    def home():
        return render_template("home.html", page_title="Generated CRUD Home", description="Use the generated sign-in and CRUD flows to explore the starter.")

    seed_items("{context["resource_name"]}", [
        {{"name": "Starter record", "status": "active", "description": "Seeded demo item"}},
        {{"name": "Draft record", "status": "draft", "description": "Another seeded demo item"}},
    ])
    return app


app = create_app()


if __name__ == "__main__":
    app.run(debug=True)
"""
    dashboard_import = f"from routes.{module} import bp as module_bp\n"
    dashboard_route = ""
    if module != "dashboard":
        dashboard_route = """
    @app.route("/dashboard")
    def dashboard():
        stats = build_dashboard_stats()
        return render_template("dashboard.html", page_title="Project Dashboard", description="A lightweight operational view for the generated starter.", stats=stats)
"""
    return f"""import os

from flask import Flask, render_template
from config import Config
from services.storage import build_dashboard_stats, init_storage
{dashboard_import}

BASE_DIR = os.path.dirname(__file__)


def create_app():
    app = Flask(
        __name__,
        template_folder=os.path.join(BASE_DIR, "templates"),
        static_folder=os.path.join(BASE_DIR, "static"),
    )
    app.config.from_object(Config)
    app.register_blueprint(module_bp)
    init_storage()

    @app.route("/")
    def home():
        return render_template("home.html", page_title="Generated App Home", description="Use the generated module or dashboard to explore the flow.")
{dashboard_route}

    return app


app = create_app()


if __name__ == "__main__":
    app.run(debug=True)
"""


def render_tests(context):
    module = "workflow" if context.get("app_family") == "workflow" else context["module"]
    app_spec = context.get("app_spec", {})
    test_plan = app_spec.get("tests", {})
    fields = list(context.get("fields", []))

    def sample_value(field):
        lowered = field.lower()
        if "email" in lowered:
            return "tester@example.com"
        if "password" in lowered:
            return "secret123"
        if lowered in {"status", "state"}:
            return "active"
        if lowered in {"priority"}:
            return "high"
        if lowered in {"rating", "score", "quantity"}:
            return "5"
        if lowered in {"dob", "date", "due_date"} or "date" in lowered:
            return "2026-04-18"
        return f"sample_{lowered}"

    def python_payload(selected_fields):
        items = ", ".join([f'"{field}": "{sample_value(field)}"' for field in selected_fields])
        return "{" + items + "}"

    if module == "workflow":
        registration_fields = []
        for form in app_spec.get("forms", []):
            if form.get("route") == "/registration":
                registration_fields = form.get("fields", [])
                break
        registration_payload = python_payload(registration_fields or ["username", "password", "first_name", "last_name", "dob"])
        return f"""from app import create_app
from services.storage import get_user_by_username


def test_home_page():
    app = create_app()
    client = app.test_client()
    response = client.get("/")
    assert response.status_code == 200


def test_registration_page():
    app = create_app()
    client = app.test_client()
    response = client.get("/registration")
    assert response.status_code == 200


def test_login_page():
    app = create_app()
    client = app.test_client()
    response = client.get("/login")
    assert response.status_code == 200


def test_dashboard_redirects_when_logged_out():
    app = create_app()
    client = app.test_client()
    response = client.get("/dashboard")
    assert response.status_code in (302, 308)


def test_workflow_registration_and_login():
    app = create_app()
    client = app.test_client()
    payload = {registration_payload}
    response = client.post("/registration", data=payload, follow_redirects=True)
    assert response.status_code == 200
    assert get_user_by_username(payload["username"]) is not None
    login = client.post("/login", data={{"username": payload["username"], "password": payload["password"]}}, follow_redirects=False)
    assert login.status_code in (302, 303)
"""
    if module in {"crud", "inventory_management", "employee_management", "customer_management", "ticket_system", "task_manager", "product_catalog"}:
        protected_route = test_plan.get("protected_routes", ["/resources"])[0]
        create_route = app_spec.get("forms", [{}])[0].get("route", protected_route + "/new")
        resource_name = context.get("resource_name")
        list_call = "list_items"
        first_field = fields[0] if fields else "name"
        create_payload = python_payload(fields)
        return f"""from app import create_app
from services.storage import {list_call}


def test_home_page():
    app = create_app()
    client = app.test_client()
    response = client.get("/")
    assert response.status_code == 200


def test_login_page():
    app = create_app()
    client = app.test_client()
    response = client.get("/login")
    assert response.status_code == 200


def test_crud_redirect_when_logged_out():
    app = create_app()
    client = app.test_client()
    response = client.get("{protected_route}")
    assert response.status_code in (302, 308)


def test_crud_login_and_dashboard():
    app = create_app()
    client = app.test_client()
    response = client.post("/login", data={{"username": "admin", "password": "admin123"}}, follow_redirects=True)
    assert response.status_code == 200
    dashboard = client.get("/dashboard")
    assert dashboard.status_code == 200


def test_crud_create_flow_persists_record():
    app = create_app()
    client = app.test_client()
    client.post("/login", data={{"username": "admin", "password": "admin123"}}, follow_redirects=True)
    payload = {create_payload}
    response = client.post("{create_route}", data=payload, follow_redirects=True)
    assert response.status_code == 200
    items = {list_call}("{resource_name}")
    assert any(item.get("{first_field}") == payload["{first_field}"] for item in items)
"""
    public_route = test_plan.get("public_routes", [f"/{module}"])[0]
    submit_route = app_spec.get("forms", [{}])[0].get("route", public_route)
    submit_payload = python_payload(fields)
    storage_import = "from services.storage import list_records"
    post_assert = 'assert any(record.get("category") == "' + module + '" for record in list_records())'
    if module == "login":
        post_assert = 'assert response.status_code == 200'
    submit_test = ""
    if module != "dashboard":
        submit_test = f"""


def test_module_submit_flow():
    app = create_app()
    client = app.test_client()
    payload = {submit_payload}
    response = client.post("{submit_route}", data=payload, follow_redirects=True)
    assert response.status_code == 200
    {post_assert}
"""
    return f"""from app import create_app
{storage_import}


def test_home_page():
    app = create_app()
    client = app.test_client()
    response = client.get("/")
    assert response.status_code == 200


def test_module_page():
    app = create_app()
    client = app.test_client()
    response = client.get("{public_route}")
    assert response.status_code == 200
{submit_test}
"""


def render_readme(context):
    module_title = context["module"].replace("_", " ").title()
    if context.get("app_family") == "workflow":
        module_title = "Workflow"
    roles = ", ".join(context.get("roles", [])) or "General user"
    workflows = ", ".join(context.get("workflows", [])) or "Standard form flow"
    constraints = ", ".join(context.get("constraints", [])) or "None explicitly parsed"
    workflow_plan = ""
    module_page = f"/{context['resource_plural'] if context.get('app_family') == 'crud' else context['module']}"
    demo_block = "- Login credentials: `admin / admin123`\n- Member credentials: `member / member123`"
    if context.get("app_family") == "workflow":
        workflow_plan = "- Workflow modules: " + " -> ".join(step["module"] for step in context.get("module_plan", [])) + "\n"
        module_page = "/registration"
        demo_block = "- Start at `/registration` to create a workflow account.\n- After registering, sign in with the same username and password."
    return f"""# {context["title"]}

Generated with the AI Code Generator.

## Stack
- Framework: {context["framework"]}
- Language: {context["language"]}
- Module: {module_title}
- Storage: {context["database"].upper()}

## Prompt Analysis
- Intent: {context.get("intent", "data_collection")}
- Roles: {roles}
- Workflows: {workflows}
- Constraints: {constraints}
- Summary: {context.get("prompt_summary", "Not available")}
{workflow_plan}

## Run
1. Create and activate a virtual environment.
2. Install dependencies with `pip install -r requirements.txt`.
3. Start the app with `python app.py`.
4. Open the local URL shown in the terminal.

## Demo
{demo_block}
- Home page: `/`
- Module page: `{module_page}`
- Dashboard: `/dashboard`
"""


def render_setup_bat():
    return """@echo off
python -m venv .venv
call .venv\\Scripts\\activate
python -m pip install --upgrade pip
python -m pip install -r requirements.txt
python app.py
"""


def render_env_example():
    return """SECRET_KEY=change-me
"""


def render_quickstart():
    return """Quick start
1. Run `setup.bat` on Windows, or create a virtual environment manually.
2. Install dependencies from `requirements.txt`.
3. Start the app with `python app.py`.
4. Open the printed local URL in your browser.
"""


def render_auth_route(module):
    return f"""from flask import Blueprint, flash, redirect, render_template, request, session, url_for

bp = Blueprint("auth", __name__)

USERS = {{
    "admin": {{"password": "admin123", "role": "admin"}},
    "member": {{"password": "member123", "role": "member"}},
}}


@bp.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        username = request.form.get("username", "").strip().lower()
        password = request.form.get("password", "").strip()
        user = USERS.get(username)
        if user and user["password"] == password:
            session["user"] = username
            session["role"] = user["role"]
            flash(f"Signed in as {{user['role']}}.", "success")
            return redirect(url_for("{module}.dashboard"))
        flash("Invalid credentials. Use one of the seeded demo accounts.", "error")
    return render_template("login.html", page_title="Workspace Login", description="Use a demo account to enter the generated CRUD workspace.")


@bp.route("/logout")
def logout():
    session.clear()
    flash("Signed out.", "success")
    return redirect(url_for("auth.login"))
"""


def render_workflow_route(context):
    modules = [step["module"] for step in context.get("module_plan", [])]
    next_map = {edge["from"]: edge["to"] for edge in context.get("workflow_edges", [])}
    registration_next = next_map.get("registration", "login")
    login_next = next_map.get("login", "dashboard")
    lines = [
        'from flask import Blueprint, flash, redirect, render_template, request, session, url_for',
        'from services.storage import append_record, build_dashboard_stats, create_user, get_user_by_username, list_records, update_user_profile',
        '',
        'bp = Blueprint("workflow", __name__)',
        '',
        'def require_login():',
        '    if "user" not in session:',
        '        flash("Sign in to continue.", "error")',
        '        return redirect(url_for("workflow.login"))',
        '    return None',
    ]

    if "registration" in modules:
        registration_fields = next(step["field_schema"] for step in context["module_plan"] if step["module"] == "registration")
        keys = [field["name"] for field in registration_fields]
        lines.extend([
            '',
            '@bp.route("/registration", methods=["GET", "POST"])',
            'def registration():',
            '    form_data = {}',
            '    if request.method == "POST":',
            f'        form_data = {{key: request.form.get(key, "").strip() for key in {keys}}}',
            '        errors = []',
            '        for required_key in ["username", "password"]:',
            '            if required_key in form_data and not form_data.get(required_key):',
            '                errors.append(f"{required_key.replace(\'_\', \' \').title()} is required.")',
            '        username = form_data.get("username", "")',
            '        if username and get_user_by_username(username):',
            '            errors.append("That username already exists.")',
            '        if errors:',
            '            for error in errors:',
            '                flash(error, "error")',
            '            return render_template("registration.html", page_title="Registration", description="Create an account to continue.", form_data=form_data)',
            '        create_user(form_data)',
            '        flash("Registration completed. Please sign in.", "success")',
            f'        return redirect(url_for("workflow.{registration_next}"))',
            '    return render_template("registration.html", page_title="Registration", description="Create an account to continue.", form_data=form_data)',
        ])

    if "login" in modules:
        lines.extend([
            '',
            '@bp.route("/login", methods=["GET", "POST"])',
            'def login():',
            '    if request.method == "POST":',
            '        username = request.form.get("username", "").strip()',
            '        password = request.form.get("password", "").strip()',
            '        user = get_user_by_username(username)',
            '        if user and user.get("password") == password:',
            '            session["user"] = username',
            '            session["role"] = user.get("role", "member")',
            '            flash("Signed in successfully.", "success")',
            f'            return redirect(url_for("workflow.{login_next}"))',
            '        flash("Invalid credentials.", "error")',
            '    return render_template("login.html", page_title="Login", description="Sign in to access your generated workflow app.")',
        ])

    if "dashboard" in modules:
        lines.extend([
            '',
            '@bp.route("/dashboard")',
            'def dashboard():',
            '    redirect_response = require_login()',
            '    if redirect_response:',
            '        return redirect_response',
            '    stats = build_dashboard_stats()',
            '    recent_entries = list_records()[:5]',
            '    return render_template("dashboard.html", page_title="Workflow Dashboard", description="A shared dashboard across the generated modules.", stats=stats, recent_entries=recent_entries)',
        ])

    if "profile" in modules:
        profile_fields = next(step["field_schema"] for step in context["module_plan"] if step["module"] == "profile")
        keys = [field["name"] for field in profile_fields]
        lines.extend([
            '',
            '@bp.route("/profile", methods=["GET", "POST"])',
            'def profile():',
            '    redirect_response = require_login()',
            '    if redirect_response:',
            '        return redirect_response',
            '    user = get_user_by_username(session["user"]) or {}',
            '    if request.method == "POST":',
            f'        form_data = {{key: request.form.get(key, "").strip() for key in {keys}}}',
            '        update_user_profile(session["user"], form_data)',
            '        flash("Profile updated.", "success")',
            f'        return redirect(url_for("workflow.{next_map.get("profile", "profile")}"))',
            '    return render_template("profile.html", page_title="Profile", description="Manage your generated account profile.", form_data=user)',
        ])

    for module_name in ("contact", "feedback"):
        if module_name in modules:
            fields = next(step["field_schema"] for step in context["module_plan"] if step["module"] == module_name)
            keys = [field["name"] for field in fields]
            lines.extend([
                '',
                f'@bp.route("/{module_name}", methods=["GET", "POST"])',
                f'def {module_name}():',
                '    redirect_response = require_login()',
                '    if redirect_response:',
                '        return redirect_response',
                '    form_data = {}',
                '    if request.method == "POST":',
                f'        form_data = {{key: request.form.get(key, "").strip() for key in {keys}}}',
                f'        append_record("{module_name}", form_data)',
                f'        flash("{module_name.title()} submitted successfully.", "success")',
                f'        return redirect(url_for("workflow.{next_map.get(module_name, "dashboard")}"))',
                f'    return render_template("{module_name}.html", page_title="{module_name.title()}", description="Generated workflow module.", form_data=form_data)',
            ])

    lines.extend([
        '',
        '@bp.route("/logout")',
        'def logout():',
        '    session.clear()',
        '    flash("Signed out.", "success")',
        '    return redirect(url_for("workflow.login"))',
        '',
    ])
    return "\n".join(lines)


def write_files(project_path, context, html_code, backend_code):
    module = "workflow" if context.get("app_family") == "workflow" else context["module"]
    html_filename = f"{module}.html"
    if context.get("app_family") == "crud":
        html_filename = f"{context['resource_name']}_overview.html"
    html_path = os.path.join(project_path, "templates", html_filename)
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html_code)

    route_path = os.path.join(project_path, "routes", f"{module}.py")
    with open(route_path, "w", encoding="utf-8") as f:
        if context.get("app_family") == "workflow":
            f.write(render_workflow_route(context))
        else:
            f.write(backend_code)

    app_path = os.path.join(project_path, "app.py")
    with open(app_path, "w", encoding="utf-8") as f:
        f.write(render_app_py(context))

    config_path = os.path.join(project_path, "config.py")
    with open(config_path, "w", encoding="utf-8") as f:
        f.write(render_config())

    base_template_path = os.path.join(project_path, "templates", "base.html")
    with open(base_template_path, "w", encoding="utf-8") as f:
        f.write(render_base_template(context["title"]))

    home_template_path = os.path.join(project_path, "templates", "home.html")
    with open(home_template_path, "w", encoding="utf-8") as f:
        f.write(render_home_template(module, context["title"]))

    success_template_path = os.path.join(project_path, "templates", "success.html")
    with open(success_template_path, "w", encoding="utf-8") as f:
        f.write(render_success_template())

    dashboard_template_path = os.path.join(project_path, "templates", "dashboard.html")
    with open(dashboard_template_path, "w", encoding="utf-8") as f:
        if context.get("app_family") == "crud":
            f.write(render_crud_dashboard_template(context["resource_name"].title(), context["database"]))
        elif context.get("app_family") == "workflow":
            module_labels = [
                (step["module"], step["module"].replace("_", " ").title())
                for step in context.get("module_plan", [])
                if step["module"] != "dashboard"
            ]
            f.write(render_workflow_dashboard_template(module_labels))
        else:
            f.write(render_dashboard_template(context["database"]))

    css_path = os.path.join(project_path, "static", "style.css")
    with open(css_path, "w", encoding="utf-8") as f:
        f.write(render_style())

    storage_path = os.path.join(project_path, "services", "storage.py")
    with open(storage_path, "w", encoding="utf-8") as f:
        if context["database"] == "sqlite":
            f.write(render_sqlite_storage_service())
        else:
            f.write(render_json_storage_service())

    requirements_path = os.path.join(project_path, "requirements.txt")
    with open(requirements_path, "w", encoding="utf-8") as f:
        f.write("flask\n")

    readme_path = os.path.join(project_path, "README.md")
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(render_readme(context))

    setup_path = os.path.join(project_path, "setup.bat")
    with open(setup_path, "w", encoding="utf-8") as f:
        f.write(render_setup_bat())

    env_path = os.path.join(project_path, ".env.example")
    with open(env_path, "w", encoding="utf-8") as f:
        f.write(render_env_example())

    quickstart_path = os.path.join(project_path, "QUICKSTART.txt")
    with open(quickstart_path, "w", encoding="utf-8") as f:
        f.write(render_quickstart())

    tests_path = os.path.join(project_path, "tests", "test_app.py")
    with open(tests_path, "w", encoding="utf-8") as f:
        f.write(render_tests(context))

    if context["database"] == "json":
        data_path = os.path.join(project_path, "data", "app_data.json")
        with open(data_path, "w", encoding="utf-8") as f:
            json.dump({"records": [], "items": {}, "users": []}, f, indent=2)

    if context.get("app_family") == "workflow":
        login_path = os.path.join(project_path, "templates", "login.html")
        with open(login_path, "w", encoding="utf-8") as f:
            f.write(render_workflow_login_template())

        for step in context.get("module_plan", []):
            module_name = step["module"]
            if module_name in {"login", "dashboard"}:
                continue
            template_path = os.path.join(project_path, "templates", f"{module_name}.html")
            with open(template_path, "w", encoding="utf-8") as f:
                submit_label = "Save and Continue"
                if module_name == "registration":
                    submit_label = "Create Account"
                elif module_name == "profile":
                    submit_label = "Save Profile"
                elif module_name in {"contact", "feedback"}:
                    submit_label = "Submit"
                f.write(
                    render_workflow_form_template(
                        module_name,
                        step["module"].replace("_", " ").title(),
                        step.get("description") or f"Generated {module_name} workflow step.",
                        step["field_schema"],
                        submit_label,
                    )
                )

    if context.get("app_family") == "crud":
        auth_route_path = os.path.join(project_path, "routes", "auth.py")
        with open(auth_route_path, "w", encoding="utf-8") as f:
            f.write(render_auth_route(module))

        resource = context["resource_name"]
        list_path = os.path.join(project_path, "templates", f"{resource}_list.html")
        with open(list_path, "w", encoding="utf-8") as f:
            f.write(
                render_crud_list_template(
                    context["field_schema"],
                    resource.title(),
                    context["resource_plural"],
                    context.get("app_spec", {}).get("filter_fields", ["status"] if "status" in context.get("fields", []) else []),
                )
            )

        form_path = os.path.join(project_path, "templates", f"{resource}_form.html")
        with open(form_path, "w", encoding="utf-8") as f:
            f.write(render_crud_form_template(resource.title(), context["resource_plural"]))

        detail_path = os.path.join(project_path, "templates", f"{resource}_detail.html")
        with open(detail_path, "w", encoding="utf-8") as f:
            f.write(render_crud_detail_template(context["field_schema"], resource.title(), context["resource_plural"]))

        login_path = os.path.join(project_path, "templates", "login.html")
        with open(login_path, "w", encoding="utf-8") as f:
            f.write(render_crud_login_template())

    return project_path


def generate_project(context, html_code, backend_code):
    project_path = create_project_structure(context["project_name"])
    write_files(project_path, context, html_code, backend_code)
    return project_path
