import os
import json


BASE_DIR = os.path.abspath("../generated_projects")


def create_project_structure(project_name):
    project_path = os.path.join(BASE_DIR, project_name)
    templates_path = os.path.join(project_path, "templates")
    routes_path = os.path.join(project_path, "routes")
    static_path = os.path.join(project_path, "static")
    services_path = os.path.join(project_path, "services")
    tests_path = os.path.join(project_path, "tests")
    data_path = os.path.join(project_path, "data")

    os.makedirs(project_path, exist_ok=True)
    os.makedirs(templates_path, exist_ok=True)
    os.makedirs(routes_path, exist_ok=True)
    os.makedirs(static_path, exist_ok=True)
    os.makedirs(services_path, exist_ok=True)
    os.makedirs(tests_path, exist_ok=True)
    os.makedirs(data_path, exist_ok=True)

    for package_path in (routes_path, services_path):
        init_path = os.path.join(package_path, "__init__.py")
        with open(init_path, "w") as f:
            f.write("")

    return project_path


def render_base_template(project_title):
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{{{ page_title or "{project_title}" }}}}</title>
    <link rel="stylesheet" href="{{{{ url_for('static', filename='style.css') }}}}">
</head>
<body>
    <header class="app-header">
        <div>
            <p class="eyebrow">{project_title}</p>
            <h1>{{{{ page_title or "{project_title}" }}}}</h1>
            <p class="subtitle">{{{{ description or "Generated by the AI Code Generator." }}}}</p>
        </div>
        <nav class="top-nav">
            <a href="{{{{ url_for('home') }}}}">Home</a>
        </nav>
    </header>
    <main class="page-shell">
        {{% with messages = get_flashed_messages(with_categories=true) %}}
            {{% if messages %}}
                <section class="flash-stack">
                {{% for category, message in messages %}}
                    <div class="flash {{'flash-success' if category == 'success' else 'flash-error'}}">{{{{ message }}}}</div>
                {{% endfor %}}
                </section>
            {{% endif %}}
        {{% endwith %}}
        {{% block content %}}{{% endblock %}}
    </main>
</body>
</html>
"""


def render_home_template(module, project_title):
    module_title = module.replace("_", " ").title()
    return f"""{{% extends "base.html" %}}
{{% block content %}}
<section class="hero-card">
    <div>
        <p class="eyebrow">Generated project</p>
        <h2>{module_title} module ready</h2>
        <p>This starter includes routes, persistence helpers, a success path, a dashboard summary, tests, and a README.</p>
        <div class="button-row">
            <a class="button primary" href="/{module}">Open module</a>
            <a class="button secondary" href="/dashboard">View dashboard</a>
        </div>
    </div>
    <div class="info-panel">
        <h3>What is included</h3>
        <ul>
            <li>Server-side validation</li>
            <li>JSON-backed sample storage</li>
            <li>Companion templates and styling</li>
            <li>Smoke tests and setup instructions</li>
        </ul>
    </div>
</section>
{{% endblock %}}
"""


def render_success_template():
    return """{% extends "base.html" %}
{% block content %}
<section class="hero-card">
    <div>
        <p class="eyebrow">Submission captured</p>
        <h2>{{ module_name }} completed successfully</h2>
        <p>The generated flow stored the submitted payload in the local JSON data store.</p>
        <div class="button-row">
            <a class="button primary" href="{{ url_for('home') }}">Back home</a>
            <a class="button secondary" href="/dashboard">Open dashboard</a>
        </div>
    </div>
    <div class="info-panel">
        <h3>Quick stats</h3>
        <ul>
            <li>Total submissions: {{ stats.total_submissions }}</li>
            <li>Active modules: {{ stats.module_count }}</li>
            <li>Stored categories: {{ stats.categories|join(', ') if stats.categories else 'None yet' }}</li>
        </ul>
    </div>
</section>
{% endblock %}
"""


def render_dashboard_template():
    return """{% extends "base.html" %}
{% block content %}
<section class="metric-grid">
    <article class="metric-card">
        <p>Total submissions</p>
        <h2>{{ stats.total_submissions }}</h2>
    </article>
    <article class="metric-card">
        <p>Active modules</p>
        <h2>{{ stats.module_count }}</h2>
    </article>
    <article class="metric-card">
        <p>Last updated</p>
        <h2>{{ stats.last_updated }}</h2>
    </article>
</section>
<section class="hero-card">
    <div>
        <h3>Recent categories</h3>
        <ul>
            {% for category in stats.categories %}
            <li>{{ category }}</li>
            {% else %}
            <li>No submissions stored yet.</li>
            {% endfor %}
        </ul>
    </div>
    <div class="info-panel">
        <h3>Storage</h3>
        <p>Data is stored locally in <code>data/app_data.json</code> for easy inspection during development.</p>
    </div>
</section>
{% endblock %}
"""


def render_style():
    return """
:root {
    --ink: #14213d;
    --teal: #0f6c7a;
    --sky: #eef6fb;
    --line: #d9e3ee;
    --card: #ffffff;
    --success: #e7f6ec;
    --error: #fde9e9;
}

* {
    box-sizing: border-box;
}

body {
    margin: 0;
    font-family: Arial, sans-serif;
    color: var(--ink);
    background: linear-gradient(180deg, #f7fbff 0%, #eef4fb 100%);
}

.app-header, .page-shell {
    max-width: 1080px;
    margin: 0 auto;
    padding-left: 24px;
    padding-right: 24px;
}

.app-header {
    padding-top: 32px;
    padding-bottom: 18px;
    display: flex;
    justify-content: space-between;
    gap: 18px;
    align-items: center;
}

.eyebrow {
    margin: 0;
    color: var(--teal);
    font-size: 12px;
    font-weight: bold;
    text-transform: uppercase;
    letter-spacing: 1px;
}

.subtitle {
    color: #536273;
}

.top-nav a {
    color: var(--ink);
    text-decoration: none;
    font-weight: bold;
}

.page-shell {
    padding-bottom: 48px;
}

.hero-card, .metric-card, .flash, form, .info-panel {
    background: var(--card);
    border-radius: 22px;
    box-shadow: 0 18px 48px rgba(20, 33, 61, 0.08);
}

.hero-card {
    display: grid;
    grid-template-columns: 1.2fr 0.8fr;
    gap: 18px;
    padding: 24px;
    margin-top: 18px;
}

.info-panel {
    padding: 20px;
}

.button-row {
    display: flex;
    flex-wrap: wrap;
    gap: 12px;
    margin-top: 18px;
}

.button {
    display: inline-block;
    padding: 12px 18px;
    border-radius: 999px;
    text-decoration: none;
    font-weight: bold;
}

.button.primary {
    background: var(--ink);
    color: white;
}

.button.secondary {
    background: #dceef1;
    color: var(--teal);
}

.flash-stack {
    display: grid;
    gap: 10px;
    margin-top: 8px;
}

.flash {
    padding: 14px 16px;
}

.flash-success {
    background: var(--success);
}

.flash-error {
    background: var(--error);
}

form {
    padding: 24px;
}

.form-grid {
    display: grid;
    grid-template-columns: repeat(2, minmax(0, 1fr));
    gap: 16px;
}

.field {
    margin-bottom: 8px;
}

.field.full {
    grid-column: 1 / -1;
}

label {
    display: block;
    font-weight: bold;
    margin-bottom: 6px;
    font-size: 13px;
}

input, textarea {
    width: 100%;
    padding: 12px 14px;
    border-radius: 14px;
    border: 1px solid var(--line);
    background: #fbfdff;
}

textarea {
    min-height: 120px;
    resize: vertical;
}

.metric-grid {
    display: grid;
    grid-template-columns: repeat(3, minmax(0, 1fr));
    gap: 18px;
    margin-top: 18px;
}

.metric-card {
    padding: 22px;
}

@media (max-width: 760px) {
    .hero-card, .metric-grid, .form-grid {
        grid-template-columns: 1fr;
    }
}
"""


def render_storage_service():
    return """import json
import os
from datetime import datetime

DATA_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "data", "app_data.json")


def _read():
    if not os.path.exists(DATA_PATH):
        return {"records": []}
    with open(DATA_PATH, "r", encoding="utf-8") as handle:
        return json.load(handle)


def _write(payload):
    with open(DATA_PATH, "w", encoding="utf-8") as handle:
        json.dump(payload, handle, indent=2)


def append_record(category, data):
    payload = _read()
    payload.setdefault("records", []).append(
        {
            "category": category,
            "data": data,
            "timestamp": datetime.utcnow().isoformat(),
        }
    )
    _write(payload)


def build_dashboard_stats():
    payload = _read()
    records = payload.get("records", [])
    categories = sorted({item["category"] for item in records})
    return {
        "total_submissions": len(records),
        "module_count": len(categories),
        "categories": categories,
        "last_updated": records[-1]["timestamp"] if records else "No activity yet",
    }
"""


def render_config():
    return """import os


class Config:
    SECRET_KEY = os.environ.get("SECRET_KEY", "dev-secret-key")
"""


def render_app_py(module):
    dashboard_import = f"from routes.{module} import bp as module_bp\n"
    dashboard_route = ""
    if module != "dashboard":
        dashboard_route = """
    @app.route("/dashboard")
    def dashboard():
        stats = build_dashboard_stats()
        return render_template("dashboard.html", page_title="Project Dashboard", description="A lightweight operational view for the generated starter.", stats=stats)
"""
    return f"""from flask import Flask, render_template
from config import Config
from services.storage import build_dashboard_stats
{dashboard_import}


def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)
    app.register_blueprint(module_bp)

    @app.route("/")
    def home():
        return render_template("home.html", page_title="Generated App Home", description="Use the generated module or dashboard to explore the flow.")
{dashboard_route}

    return app


app = create_app()


if __name__ == "__main__":
    app.run(debug=True)
"""


def render_tests(module):
    return f"""from app import create_app


def test_home_page():
    app = create_app()
    client = app.test_client()
    response = client.get("/")
    assert response.status_code == 200


def test_module_page():
    app = create_app()
    client = app.test_client()
    response = client.get("/{module}")
    assert response.status_code == 200
"""


def render_readme(context):
    module_title = context["module"].replace("_", " ").title()
    roles = ", ".join(context.get("roles", [])) or "General user"
    workflows = ", ".join(context.get("workflows", [])) or "Standard form flow"
    constraints = ", ".join(context.get("constraints", [])) or "None explicitly parsed"
    return f"""# {context["title"]}

Generated with the AI Code Generator.

## Stack
- Framework: {context["framework"]}
- Language: {context["language"]}
- Module: {module_title}
- Storage: Local JSON file in `data/app_data.json`

## Prompt Analysis
- Intent: {context.get("intent", "data_collection")}
- Roles: {roles}
- Workflows: {workflows}
- Constraints: {constraints}
- Summary: {context.get("prompt_summary", "Not available")}

## Run
1. Create and activate a virtual environment.
2. Install dependencies with `pip install -r requirements.txt`.
3. Start the app with `python app.py`.
4. Open the local URL shown in the terminal.

## Demo
- Login credentials: `admin / admin123`
- Home page: `/`
- Module page: `/{context["module"]}`
- Dashboard: `/dashboard`
"""


def render_setup_bat():
    return """@echo off
python -m venv .venv
call .venv\\Scripts\\activate
python -m pip install --upgrade pip
python -m pip install -r requirements.txt
python app.py
"""


def render_env_example():
    return """SECRET_KEY=change-me
"""


def render_quickstart():
    return """Quick start
1. Run `setup.bat` on Windows, or create a virtual environment manually.
2. Install dependencies from `requirements.txt`.
3. Start the app with `python app.py`.
4. Open the printed local URL in your browser.
"""


def write_files(project_path, context, html_code, backend_code):
    module = context["module"]
    html_path = os.path.join(project_path, "templates", f"{module}.html")
    with open(html_path, "w", encoding="utf-8") as f:
        f.write(html_code)

    route_path = os.path.join(project_path, "routes", f"{module}.py")
    with open(route_path, "w", encoding="utf-8") as f:
        f.write(backend_code)

    app_path = os.path.join(project_path, "app.py")
    with open(app_path, "w", encoding="utf-8") as f:
        f.write(render_app_py(module))

    config_path = os.path.join(project_path, "config.py")
    with open(config_path, "w", encoding="utf-8") as f:
        f.write(render_config())

    base_template_path = os.path.join(project_path, "templates", "base.html")
    with open(base_template_path, "w", encoding="utf-8") as f:
        f.write(render_base_template(context["title"]))

    home_template_path = os.path.join(project_path, "templates", "home.html")
    with open(home_template_path, "w", encoding="utf-8") as f:
        f.write(render_home_template(module, context["title"]))

    success_template_path = os.path.join(project_path, "templates", "success.html")
    with open(success_template_path, "w", encoding="utf-8") as f:
        f.write(render_success_template())

    dashboard_template_path = os.path.join(project_path, "templates", "dashboard.html")
    with open(dashboard_template_path, "w", encoding="utf-8") as f:
        f.write(render_dashboard_template())

    css_path = os.path.join(project_path, "static", "style.css")
    with open(css_path, "w", encoding="utf-8") as f:
        f.write(render_style())

    storage_path = os.path.join(project_path, "services", "storage.py")
    with open(storage_path, "w", encoding="utf-8") as f:
        f.write(render_storage_service())

    requirements_path = os.path.join(project_path, "requirements.txt")
    with open(requirements_path, "w", encoding="utf-8") as f:
        f.write("flask\n")

    readme_path = os.path.join(project_path, "README.md")
    with open(readme_path, "w", encoding="utf-8") as f:
        f.write(render_readme(context))

    setup_path = os.path.join(project_path, "setup.bat")
    with open(setup_path, "w", encoding="utf-8") as f:
        f.write(render_setup_bat())

    env_path = os.path.join(project_path, ".env.example")
    with open(env_path, "w", encoding="utf-8") as f:
        f.write(render_env_example())

    quickstart_path = os.path.join(project_path, "QUICKSTART.txt")
    with open(quickstart_path, "w", encoding="utf-8") as f:
        f.write(render_quickstart())

    tests_path = os.path.join(project_path, "tests", "test_app.py")
    with open(tests_path, "w", encoding="utf-8") as f:
        f.write(render_tests(module))

    data_path = os.path.join(project_path, "data", "app_data.json")
    with open(data_path, "w", encoding="utf-8") as f:
        json.dump({"records": []}, f, indent=2)

    return project_path


def generate_project(context, html_code, backend_code):
    project_path = create_project_structure(context["project_name"])
    write_files(project_path, context, html_code, backend_code)
    return project_path
